name: Deploy5

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x]
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # # Setup key
      # - run: set -eu
      # - run: mkdir "$HOME/.ssh"
      # - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      # - run: chmod 600 "$HOME/.ssh/key"
      # # Build
      # - run: npm ci
      # - run: npm run build
      # # Deploy
      # - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . pepelsbey@pepelsbey.dev:/var/www/pepelsbey.dev/html/

      # - uses: actions/checkout@master
      # - name: Push to server
        # uses: appleboy/ssh-action@master
        # with:
        #   host: ${{ secrets.SERVER_IP }}
        #   username: ${{ secrets.SERVER_USERNAME }}
        #   password: ${{ secrets.SERVER_PASSWORD }}
        # #   # script: cd ${{ secrets.PROJECT_PATH }} && git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/susomejias/portfolio.git master && npm install && ng build --prod && cp htaccess dist/portfolio/
        # #   script: cd ${{ secrets.PROJECT_PATH }} && git pull https://github.com/nyosru/bu-back.git main && /opt/php74/bin/php composer.phar i && npm install && npm run build
        #   script: cd ${{ secrets.P
        

      - name: pull on server
        uses: appleboy/ssh-action@master
        with:
          # host: ${{ secrets.HOST }}
          host: ${{ secrets.SERVER_IP }}
          # username: ${{ secrets.USERNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # port: ${{ secrets.PORT }}
          # script: ls
          # script: cd ${{ secrets.PROJECT_PATH }} && git pull https://github.com/nyosru/bu-back.git main --force
          # script: cd www && cd gg && git pull https://github.com/nyosru/bu-back.git main --force
          # script: cd www && cd gg && git pull
          # script: cd www && cd gg && git stash save && git merge origin/main && git stash pop
          # script: cd www && cd gg && git pull https://github.com/nyosru/bu-back.git main -f > /dev/null
          # script: cd www && cd gg && git pull https://github.com/nyosru/bu-back.git main --rebase:true > /dev/null
          # script: cd www && cd gg && git pull https://github.com/nyosru/bu-back.git main --rebase
          # script: cd www && cd gg && git pull git@github.com:nyosru/bu-back.git
          script: cd www && cd gg && git config --global user.email "1@php-cat.com" && git config --global user.name "Sergey" && git reset --hard && git stash save && git pull https://github.com/nyosru/bu-back.git main --force && git stash pop
          

      # - name: Install 🔧
      #   run: npm install

      # - name: Run Test 🔨
      #   run: npm run test
